### ISSUE TITLE
avg is not working

### ISSUE THREAD

**Issue by l736k** [kcdr/flot-autoMarkings#5]
while "showAvg" is working correctly, if i set "avg" preperty (instead of "showAvg") it won't show anything

**Comment by kcdr** [comment]
Property "avg" is for setting the value of the average line. For it being used you have to set "showAvg" to true.

**Comment by l736k** [comment]
it won't work anyway. this is my code: "autoMarkings: { enabled: true, showAvg: true, avg: 3.2 }" and the average line ignores completely the "avg" value. it just appear as if only the "showAvg: true" is set (something less than 1.24). I attach a screenshot.
![flot](https://cloud.githubusercontent.com/assets/6198951/5746800/a1f189e2-9c32-11e4-9b88-eafd248b61b0.png)
